using Microsoft.Xna.Framework.Audio;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Media;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Mono_Ether {
    static class Art {
        public static Texture2D Glow;
        public static Texture2D Geom;
        public static Texture2D Heart;
        public static Texture2D Pixel;
        public static Texture2D Player;
        public static Texture2D YouWon;
        public static Texture2D Bullet;
        public static Texture2D PauseBg;
        public static Texture2D Default;
        public static Texture2D YouDied;
        public static Texture2D TileSus;
        public static Texture2D Pointer;
        public static Texture2D BossOne;
        public static Texture2D TileDirt;
        public static Texture2D SnakeBody;
        public static Texture2D PauseExit;
        public static Texture2D SnakeHead;
        public static Texture2D StarBurst;
        public static Texture2D TileGrass;
        public static Texture2D TileStone;
        public static Texture2D BlueSeeker;
        public static Texture2D PinkSeeker;
        public static Texture2D GreenSeeker;
        public static Texture2D PauseResume;
        public static Texture2D CollisionUp;
        public static Texture2D WelcomeText;
        public static Texture2D BossOneChild;
        public static Texture2D PinkWanderer;
        public static Texture2D LineParticle;
        public static Texture2D CollisionLeft;
        public static Texture2D CollisionDown;
        public static Texture2D BackAndForther;
        public static Texture2D PurpleWanderer;
        public static Texture2D CollisionRight;
        public static Texture2D PinkSeekerChild;
        public static Texture2D MenuButtonBlank;
        public static Texture2D CollisionTopLeft;
        public static Texture2D CollisionTopRight;
        public static Texture2D BackgroundParticle;        
        public static Texture2D SettingsSliderLeft;
        public static Texture2D SettingsSliderBall;
        public static Texture2D SettingsSliderRight;
        public static Texture2D CollisionBottomLeft;
        public static Texture2D CollisionBottomRight;
        public static Texture2D SettingsSliderMiddle;
        public static Texture2D PowerMoveSpeedIncrease;
        public static Texture2D PowerMoveSpeedDecrease;
        public static Texture2D PowerShootSpeedIncrease;
        public static Texture2D PowerShootSpeedDecrease;
        public static void Load(ContentManager content) {
            Pixel = content.Load<Texture2D>("Textures/Menu/pixel");
            Glow = content.Load<Texture2D>("Textures/Gameplay/Glow");
            Geom = content.Load<Texture2D>("Textures/GamePlay/Geom");
            TileSus = content.Load<Texture2D>("Textures/tiles/tile4");
            Heart = content.Load<Texture2D>("Textures/GamePlay/Heart");
            TileDirt = content.Load<Texture2D>("Textures/tiles/tile2");
            TileGrass = content.Load<Texture2D>("Textures/tiles/tile1");
            TileStone = content.Load<Texture2D>("Textures/tiles/tile3");
            Player = content.Load<Texture2D>("Textures/Gameplay/Player");
            Bullet = content.Load<Texture2D>("Textures/Gameplay/Bullet");
            YouWon = content.Load<Texture2D>("Textures/Gameplay/YouWon");
            Default = content.Load<Texture2D>("Textures/Gameplay/Default");
            BossOne = content.Load<Texture2D>("Textures/GamePlay/BossOne");
            YouDied = content.Load<Texture2D>("Textures/Gameplay/youDied");
            Pointer = content.Load<Texture2D>("Textures/Gameplay/Pointer");
            PauseBg = content.Load<Texture2D>("Textures/GamePause/pause_bg");
            LineParticle = content.Load<Texture2D>("Textures/Gameplay/Laser");
            SnakeHead = content.Load<Texture2D>("Textures/GamePlay/SnakeHead");
            SnakeBody = content.Load<Texture2D>("Textures/GamePlay/SnakeBody");
            StarBurst = content.Load<Texture2D>("Textures/Gameplay/StarBurst");
            CollisionUp = content.Load<Texture2D>("Textures/tiles/collisionUp");
            BlueSeeker = content.Load<Texture2D>("Textures/Gameplay/BlueSeeker");
            PinkSeeker = content.Load<Texture2D>("Textures/Gameplay/PinkSeeker");
            WelcomeText = content.Load<Texture2D>("Textures/Intro/welcome_text");
            PauseExit = content.Load<Texture2D>("Textures/GamePause/exit_button");
            GreenSeeker = content.Load<Texture2D>("Textures/Gameplay/GreenSeeker");
            CollisionDown = content.Load<Texture2D>("Textures/tiles/collisionDown");
            CollisionLeft = content.Load<Texture2D>("Textures/tiles/collisionLeft");
            BossOneChild = content.Load<Texture2D>("Textures/GamePlay/BossOneChild");
            PinkWanderer = content.Load<Texture2D>("Textures/Gameplay/PinkWanderer");
            CollisionRight = content.Load<Texture2D>("Textures/tiles/collisionRight");
            PauseResume = content.Load<Texture2D>("Textures/GamePause/resume_button");
            SettingsSliderBall = content.Load<Texture2D>("Textures/Menu/slider_ball");
            BackAndForther = content.Load<Texture2D>("Textures/GamePlay/BackAndForther");
            MenuButtonBlank = content.Load<Texture2D>("Textures/Menu/menu_button_blank");
            PurpleWanderer = content.Load<Texture2D>("Textures/Gameplay/PurpleWanderer");
            CollisionTopLeft = content.Load<Texture2D>("Textures/tiles/collisionTopLeft");
            SettingsSliderLeft = content.Load<Texture2D>("Textures/Menu/slider_bar_left");
            SettingsSliderMiddle = content.Load<Texture2D>("Textures/Menu/slider_middle");
            PinkSeekerChild = content.Load<Texture2D>("Textures/Gameplay/PinkSeekerChild");
            CollisionTopRight = content.Load<Texture2D>("Textures/tiles/collisionTopRight");
            SettingsSliderRight = content.Load<Texture2D>("Textures/Menu/slider_bar_right");
            CollisionBottomLeft = content.Load<Texture2D>("Textures/tiles/collisionBottomLeft");
            BackgroundParticle = content.Load<Texture2D>("Textures/GamePlay/BackgroundParticle");
            CollisionBottomRight = content.Load<Texture2D>("Textures/tiles/collisionBottomRight");
            PowerMoveSpeedIncrease = content.Load<Texture2D>("Textures/GamePlay/PowerMoveSpeedIncrease");
            PowerMoveSpeedDecrease = content.Load<Texture2D>("Textures/GamePlay/PowerMoveSpeedDecrease");
            PowerShootSpeedIncrease = content.Load<Texture2D>("Textures/GamePlay/PowerShootSpeedIncrease");
            PowerShootSpeedDecrease = content.Load<Texture2D>("Textures/GamePlay/PowerShootSpeedDecrease");
        }
    }
}