using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using System.Linq;

namespace Mono_Ether {
    static class Art {
        public static Texture2D Glow;
        public static Texture2D Geom;
        public static Texture2D Heart;
        public static Texture2D Pixel;
        public static Texture2D Drone;
        public static Texture2D Player;
        public static Texture2D YouWon;
        public static Texture2D Bullet;
        public static Texture2D PauseBg;
        public static Texture2D Default;
        public static Texture2D YouDied;
        public static Texture2D TileSus;
        public static Texture2D Pointer;
        public static Texture2D BossOne;
        public static Texture2D TileDirt;
        public static Texture2D SnakeBody;
        public static Texture2D PauseExit;
        public static Texture2D SnakeHead;
        public static Texture2D StarBurst;
        public static Texture2D TileGrass;
        public static Texture2D TileStone;
        public static Texture2D BlueSeeker;
        public static Texture2D PinkSeeker;
        public static Texture2D BossTwoHead;
        public static Texture2D BossTwoTail;
        public static Texture2D GreenSeeker;
        public static Texture2D PauseResume;
        public static Texture2D CollisionUp;
        public static Texture2D WelcomeText;
        public static Texture2D BossOneChild;
        public static Texture2D PinkWanderer;
        public static Texture2D LineParticle;
        public static Texture2D CollisionLeft;
        public static Texture2D CollisionDown;
        public static Texture2D BackAndForther;
        public static Texture2D PurpleWanderer;
        public static Texture2D CollisionRight;
        public static Texture2D PinkSeekerChild;
        public static Texture2D MenuButtonBlank;
        public static Texture2D CollisionTopLeft;
        public static Texture2D CollisionTopRight;
        public static Texture2D BackgroundParticle;
        public static Texture2D SettingsSliderLeft;
        public static Texture2D SettingsSliderBall;
        public static Texture2D SettingsSliderRight;
        public static Texture2D CollisionBottomLeft;
        public static Texture2D CollisionBottomRight;
        public static Texture2D SettingsSliderMiddle;
        public static Texture2D PowerMoveSpeedIncrease;
        public static Texture2D PowerMoveSpeedDecrease;
        public static Texture2D PowerShootSpeedIncrease;
        public static Texture2D PowerShootSpeedDecrease;

        public static Texture2D[] BossThree;
        public static void Load(ContentManager content) {
            Pixel = content.Load<Texture2D>("Textures/Menu/pixel");
            Glow = content.Load<Texture2D>("Textures/Gameplay/Glow");
            Geom = content.Load<Texture2D>("Textures/Gameplay/Geom");
            TileSus = content.Load<Texture2D>("Textures/Tiles/tile_4");
            Heart = content.Load<Texture2D>("Textures/Gameplay/Heart");
            Drone = content.Load<Texture2D>("Textures/Gameplay/Drone");
            TileDirt = content.Load<Texture2D>("Textures/Tiles/tile_2");
            TileGrass = content.Load<Texture2D>("Textures/Tiles/tile_1");
            TileStone = content.Load<Texture2D>("Textures/Tiles/tile_3");
            Player = content.Load<Texture2D>("Textures/Gameplay/Player");
            Bullet = content.Load<Texture2D>("Textures/Gameplay/Bullet");
            YouWon = content.Load<Texture2D>("Textures/Gameplay/YouWon");
            Default = content.Load<Texture2D>("Textures/Gameplay/Default");
            BossOne = content.Load<Texture2D>("Textures/Gameplay/BossOne");
            YouDied = content.Load<Texture2D>("Textures/Gameplay/YouDied");
            Pointer = content.Load<Texture2D>("Textures/Gameplay/Pointer");
            PauseBg = content.Load<Texture2D>("Textures/Gamepause/pause_bg");
            LineParticle = content.Load<Texture2D>("Textures/Gameplay/Laser");
            SnakeHead = content.Load<Texture2D>("Textures/Gameplay/SnakeHead");
            SnakeBody = content.Load<Texture2D>("Textures/Gameplay/SnakeBody");
            StarBurst = content.Load<Texture2D>("Textures/Gameplay/StarBurst");
            CollisionUp = content.Load<Texture2D>("Textures/Tiles/collision_up");
            BlueSeeker = content.Load<Texture2D>("Textures/Gameplay/BlueSeeker");
            PinkSeeker = content.Load<Texture2D>("Textures/Gameplay/PinkSeeker");
            WelcomeText = content.Load<Texture2D>("Textures/Intro/welcome_text");
            PauseExit = content.Load<Texture2D>("Textures/Gamepause/exit_button");
            GreenSeeker = content.Load<Texture2D>("Textures/Gameplay/GreenSeeker");
            BossTwoHead = content.Load<Texture2D>("Textures/Gameplay/BossTwoHead");
            BossTwoTail = content.Load<Texture2D>("Textures/Gameplay/BossTwoTail");
            CollisionDown = content.Load<Texture2D>("Textures/Tiles/collision_down");
            CollisionLeft = content.Load<Texture2D>("Textures/Tiles/collision_left");
            BossOneChild = content.Load<Texture2D>("Textures/Gameplay/BossOneChild");
            PinkWanderer = content.Load<Texture2D>("Textures/Gameplay/PinkWanderer");
            CollisionRight = content.Load<Texture2D>("Textures/Tiles/collision_right");
            PauseResume = content.Load<Texture2D>("Textures/Gamepause/resume_button");
            SettingsSliderBall = content.Load<Texture2D>("Textures/Menu/slider_ball");
            BackAndForther = content.Load<Texture2D>("Textures/Gameplay/BackAndForther");
            MenuButtonBlank = content.Load<Texture2D>("Textures/Menu/menu_button_blank");
            PurpleWanderer = content.Load<Texture2D>("Textures/Gameplay/PurpleWanderer");
            CollisionTopLeft = content.Load<Texture2D>("Textures/Tiles/collision_top_left");
            SettingsSliderLeft = content.Load<Texture2D>("Textures/Menu/slider_bar_left");
            SettingsSliderMiddle = content.Load<Texture2D>("Textures/Menu/slider_middle");
            PinkSeekerChild = content.Load<Texture2D>("Textures/Gameplay/PinkSeekerChild");
            CollisionTopRight = content.Load<Texture2D>("Textures/Tiles/collision_top_right");
            SettingsSliderRight = content.Load<Texture2D>("Textures/Menu/slider_bar_right");
            CollisionBottomLeft = content.Load<Texture2D>("Textures/Tiles/collision_bottom_left");
            BackgroundParticle = content.Load<Texture2D>("Textures/Gameplay/BackgroundParticle");
            CollisionBottomRight = content.Load<Texture2D>("Textures/Tiles/collision_bottom_right");
            PowerMoveSpeedIncrease = content.Load<Texture2D>("Textures/Gameplay/PowerMoveSpeedIncrease");
            PowerMoveSpeedDecrease = content.Load<Texture2D>("Textures/Gameplay/PowerMoveSpeedDecrease");
            PowerShootSpeedIncrease = content.Load<Texture2D>("Textures/Gameplay/PowerShootSpeedIncrease");
            PowerShootSpeedDecrease = content.Load<Texture2D>("Textures/Gameplay/PowerShootSpeedDecrease");

            BossThree = Enumerable.Range(1, 8).Select(x => content.Load<Texture2D>("Textures/Gameplay/BossThree/BossThree_" + x)).ToArray();
        }
    }
}